<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FoodProduct;

class FoodProductSeeder extends Seeder
{
    public function run()
    {
        FoodProduct::truncate();
        FoodProduct::insert([
            [
                'brand' => 'Royal Canin',
                'title' => 'Adult Dog Food - Chicken & Rice',
                'description' => 'Complete nutrition for adult dogs with high-quality protein and essential nutrients.',
                'pet_type' => 'dog',
                'age_group' => 'adult',
                'food_type' => 'dry',
                'price' => 850,
                'old_price' => 950,
                'stock_quantity' => 50,
                'image' => 'https://shop.royalcanin.ca/cdn/shop/products/n5ue7pedongc7yiawvq0.jpg?v=1609254626&width=1500',
                'badge' => 'Popular',
                'rating' => 4.8,
                'is_active' => 1,
                'weight' => '2kg',
            ],
            [
                'brand' => 'Whiskas',
                'title' => 'Cat Food - Tuna in Gravy',
                'description' => 'Delicious wet food with real tuna pieces in savory gravy, perfect for adult cats.',
                'pet_type' => 'cat',
                'age_group' => 'adult',
                'food_type' => 'wet',
                'price' => 450,
                'old_price' => null,
                'stock_quantity' => 40,
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqvJIF9kBdHPQT5CoA69Z2zq1pBoHnfqgKkw&s',
                'badge' => 'New',
                'rating' => 4.6,
                'is_active' => 1,
                'weight' => '400g',
            ],
            [
                'brand' => 'Pedigree',
                'title' => 'Puppy Food - Chicken & Milk',
                'description' => 'Specially formulated for growing puppies with calcium and DHA for healthy development.',
                'pet_type' => 'dog',
                'age_group' => 'puppy',
                'food_type' => 'dry',
                'price' => 1200,
                'old_price' => 1350,
                'stock_quantity' => 30,
                'image' => 'https://m.media-amazon.com/images/I/81HfEtQtIDL._UF1000,1000_QL80_.jpg',
                'badge' => 'Premium',
                'rating' => 4.7,
                'is_active' => 1,
                'weight' => '3kg',
            ],
            [
                'brand' => 'Vitakraft',
                'title' => 'Bird Seed Mix - Premium Blend',
                'description' => 'Natural seed mix with sunflower seeds, millet, and dried fruits for all bird types.',
                'pet_type' => 'bird',
                'age_group' => 'adult',
                'food_type' => 'treats',
                'price' => 320,
                'old_price' => null,
                'stock_quantity' => 20,
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbwYG54uIkxneJ3nyqOfPmkcHBO6W1AB7K8Q&s',
                'badge' => 'Organic',
                'rating' => 4.5,
                'is_active' => 1,
                'weight' => '500g',
            ],
            [
                'brand' => "Hill's Science Diet",
                'title' => 'Senior Cat Food - Chicken',
                'description' => 'Specially formulated for senior cats with easy-to-digest ingredients and joint support.',
                'pet_type' => 'cat',
                'age_group' => 'senior',
                'food_type' => 'dry',
                'price' => 950,
                'old_price' => 1100,
                'stock_quantity' => 15,
                'image' => 'https://pxmshare.colgatepalmolive.com/JPEG_1500/R1smRgNvhXECmYV_qdHdo.jpg',
                'badge' => 'Senior',
                'rating' => 4.9,
                'is_active' => 1,
                'weight' => '1.5kg',
            ],
            [
                'brand' => 'Oxbow',
                'title' => 'Rabbit Pellets - Timothy Hay',
                'description' => 'High-fiber pellets made from timothy hay, perfect for adult rabbit nutrition.',
                'pet_type' => 'rabbit',
                'age_group' => 'adult',
                'food_type' => 'dry',
                'price' => 680,
                'old_price' => null,
                'stock_quantity' => 10,
                'image' => 'https://images-cdn.ubuy.co.id/65b4a8dfd4f9a162d5662ca8-menu-premium-rabbit-food-timothy-hay.jpg',
                'badge' => 'Natural',
                'rating' => 4.4,
                'is_active' => 1,
                'weight' => '1kg',
            ],
            [
                'brand' => 'Pedigree',
                'title' => 'Dentastix - Dental Treats',
                'description' => 'Daily dental care treats that help reduce tartar buildup and freshen breath.',
                'pet_type' => 'dog',
                'age_group' => 'adult',
                'food_type' => 'treats',
                'price' => 380,
                'old_price' => 420,
                'stock_quantity' => 25,
                'image' => 'https://images.albertsons-media.com/is/image/ABS/960225872?$ng-ecom-pdp-desktop$&defaultImage=Not_Available',
                'badge' => 'Bestseller',
                'rating' => 4.6,
                'is_active' => 1,
                'weight' => '28 Sticks',
            ],
            [
                'brand' => 'Tetra',
                'title' => 'Tropical Fish Flakes',
                'description' => 'Complete nutrition for tropical fish with enhanced colors and vitality.',
                'pet_type' => 'fish',
                'age_group' => 'adult',
                'food_type' => 'dry',
                'price' => 280,
                'old_price' => null,
                'stock_quantity' => 18,
                'image' => 'https://static-01.daraz.com.bd/p/692b29da77a63c12c2d2a1b6d403bb48.jpg',
                'badge' => 'Aquatic',
                'rating' => 4.3,
                'is_active' => 1,
                'weight' => '200g',
            ],
        ]);
    }
}
